import { initializeApp } from 'firebase/app';
import { 
  getAuth, 
  signInAnonymously, 
  signOut, 
  onAuthStateChanged,
  signInWithEmailAndPassword,
  createUserWithEmailAndPassword,
  updateProfile,
  User
} from 'firebase/auth';
import { 
  getFirestore, 
  doc, 
  getDoc, 
  setDoc, 
  updateDoc, 
  collection, 
  getDocs, 
  query, 
  orderBy, 
  limit, 
  increment, 
  arrayUnion,
  runTransaction,
  writeBatch
} from 'firebase/firestore';

// We import the configuration file that was auto-generated by set_up_firebase
import firebaseConfig from '../../firebase-applet-config.json';

// Resolve environment variables with fallback to firebase-applet-config.json
const finalConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY || firebaseConfig.apiKey || "",
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN || firebaseConfig.authDomain || "",
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID || firebaseConfig.projectId || "",
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET || firebaseConfig.storageBucket || "",
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID || firebaseConfig.messagingSenderId || "",
  appId: import.meta.env.VITE_FIREBASE_APP_ID || firebaseConfig.appId || "",
  firestoreDatabaseId: import.meta.env.VITE_FIREBASE_FIRESTORE_DATABASE_ID || firebaseConfig.firestoreDatabaseId || "",
};

// Check if Firebase is configured with real credentials
export const isFirebaseConfigured = !!(
  finalConfig.apiKey &&
  finalConfig.apiKey !== "YOUR_API_KEY" &&
  finalConfig.projectId &&
  finalConfig.appId
);

let app: any;
let auth: any;
let db: any;
let isFirebaseAvailable = false;

try {
  if (isFirebaseConfigured) {
    app = initializeApp(finalConfig);
    auth = getAuth(app);
    db = getFirestore(app, finalConfig.firestoreDatabaseId || undefined);
    isFirebaseAvailable = true;
    console.log('[Firebase Init] Successfully initialized Firebase!');
  } else {
    // Prevent crashes when unconfigured
    const dummyConfig = {
      apiKey: "dummy-api-key-to-prevent-boot-crash",
      authDomain: "dummy-auth-domain.firebaseapp.com",
      projectId: "dummy-project-id",
      storageBucket: "dummy-storage-bucket.appspot.com",
      messagingSenderId: "000000000000",
      appId: "1:000000000000:web:000000000000",
    };
    app = initializeApp(dummyConfig);
    auth = getAuth(app);
    db = getFirestore(app);
    isFirebaseAvailable = false;
    console.warn('[Firebase Init] Firebase not configured. Offline mode enabled.');
  }
} catch (error) {
  console.error('[Firebase Init] Failed to initialize Firebase:', error);
  isFirebaseAvailable = false;
  try {
    const backupConfig = {
      apiKey: "dummy-api-key-to-prevent-boot-crash",
      authDomain: "dummy-auth-domain.firebaseapp.com",
      projectId: "dummy-project-id",
      storageBucket: "dummy-storage-bucket.appspot.com",
      messagingSenderId: "000000000000",
      appId: "1:000000000000:web:000000000000",
    };
    app = initializeApp(backupConfig);
    auth = getAuth(app);
    db = getFirestore(app);
  } catch (e) {
    app = {} as any;
    auth = {
      onAuthStateChanged: () => () => {},
      signInAnonymously: () => Promise.reject(new Error("Auth unavailable")),
    } as any;
    db = {} as any;
  }
}

export {
  app,
  auth,
  db,
  isFirebaseAvailable,

  signInAnonymously,
  signOut,
  onAuthStateChanged,
  signInWithEmailAndPassword,
  createUserWithEmailAndPassword,
  updateProfile,
  doc,
  getDoc,
  setDoc,
  updateDoc,
  collection,
  getDocs,
  query,
  orderBy,
  limit,
  increment,
  arrayUnion,
  runTransaction,
  writeBatch
};
export type { User };
